### ISSUE TITLE
API (re)design

### ISSUE THREAD

**Issue by HDembinski** [sweights/sweights#8]
This is incomplete, but it is a start.

# General principles

## Moving to functional API

The current API uses an object-oriented approach, I propose to move to a functional API. Objects are great for data objects, but not well suitable for transformation algorithms. For transformations (data goes in, data goes out), it is natural to use functions. Functions are easier to reason about, since they do not have state, and they communicate clearly that you can run them in parallel and that they do not have other hidden dependencies. Since objects are so powerful, all this is not so clear when you have an object. In C++, it sometimes makes sense to use an object (functor), because C++ does not have keyword based arguments and passing a lot of positional arguments gets confusing. So people sometimes use classes in C++ if you need to set a lot of parameters for an algorithm, you can do that more elegantly with methods. In Python, this is not necessary. In this language it is normal for functions to have potentially lots of optional keyword-based arguments.

Examples of popular libraries with a functional API in Python: numpy, scipy, matplotlib.

## Low-level and high-level functions

We want to accommodate casual and power users. For casual users we need high-level functions that take inputs and produce directly what most people need. These high-level functions should call a bunch of low-level functions which we also include to accommodate power users. Power users want to be able to replace parts of the calculations with their own stuff or have advanced use cases where they may want to avoid superfluous calculations that the high-level functions may do.

Here is a rough example. To compute sweights, we need the W matrix. So there should be a high-level function that takes the component pdfs, an array containing the discriminating variable and then returns an array with the sweights. There should also be a low-level function that just computes the W matrix, which is called internally by the high-level function.

**Comment by matthewkenzie** [comment]
Yes this makes sense and I agree. This will not be back-compatible so once done will require a new series.

**Comment by HDembinski** [comment]
There are two ways do handle this. Breaking change, which is ok, since this is not even a v1.0 release. It is nice to announce this, though. The other option is to use different names for the new api or put the new api in differently named submodules and instruct people to import from there, then nag people who use the old api with `VisibleDeprecationWarning`s, which can be imported from `numpy`.

**Comment by matthewkenzie** [comment]
Haven't got round to this yet but plan to shortly. I think we will need to leave the class functionality as it is because often one wants to actually extract the weight function (requires inputs pdfs and in some cases the dataset) but apply these to a different dataset (i.e. to plot the weight functions). I suppose one option is for the API functionality to return a callable. But in terms of a simple function to return the weights given some pdfs and a dataset, I think the most straightforward here is to:

- [ ] Add a function(s) to the `sweights` module such as `sweight()` and `cow()` which take similar parameters to those that are passed to the `SWeight()` and `Cow()` classes.
- [ ] These functions can then just make one of the class objects and return the weights.
- [ ] Can have an option about what is returned (i.e. `(N,)` vector for just one set of weights on N events or  `(N,M)`  for M different components)

**Comment by HDembinski** [comment]
I am looking into this again, since someone in my group wants to use sweights.

I can see why the `sweights` function should return a weight function and not a weight vector, I will keep that in mind.

I am just looking at the class `SWeights` for now. We can redesign class `Cow` in a similar way. I think need to merge the two, because sweights computation is a special case of cow computation that should also be reflected in the code. Plus, it reduces redundancy.

There are other ways to improve the current API. We said that the class `SWeight` will be replaced by a function `sweight` with similar parameters, but I think that `SWeight.__init__` offers too many options. Some of them should be removed. I would also rename some of the parameters.
- Parameters that are mandatory should **not** have default values: `pdfs`, `yields`
- `discvarranges` can be discovered from np.min, np.max of `data` if it is not provided. The current default -np.inf, np.inf is not a good choice, because it is never correct in practice. This should be renamed to `range` following `np.histogram`
- `method`
  - "tsplot" should be removed. We should not provide a wrapper over ROOT code. This was probably useful during development, but we should not offer this to our users. We know that our method is correct etc, so we don't need to offer calls into ROOT code.
  - "roofit" should be removed, same reason as for "tsplot". We could and probably should provide a wrapper for RooFit users so that they can pass their unmodified RooFit objects into our function. This function call could like in a submodule `sweights.roofit`. Allows users to pass the RooFit objects directly has advantages, because we can query them for needed info like the ranges.
  - "subhess": Do we need to offer this? It is less accurate than "summation", but otherwise identical. In practice, is there a situation where the user want to use the covariance matrix? I think it is difficult to guarantee that the user provides the correct covariance matrix, and we also then need additional interface to mark the indices that contain the yields. I think that we should offer a separate function to compute SWeights from the covariance matrix if we cannot drop this. It should be part of the main API.
  - Do we need "integration"? Or is "summation" sufficient? If not, let's remove `method` altogether.
- `compnames`: Should be removed. Every function should have a single purpose, plotting and sweight computation should be done by separate functions, since the plotting does not need access to details that are only available during the sweight computation. We can provide standard plotting functions for convenience in a `mpl` submodule.
- `alphas` can be removed, since "subhess" will be either removed or this functionality will be moved to a separate function/class.
- `rfobs` can be removed, because we remove the "roofit" option in `method`
- `verbose` should be removed. Basic mathematical functions should silently do their thing unless there is a warning/error, and then use the `warnings` module or raise an exception in Python.
- `checks` should be removed. The checks which are currently implemented do not seem to use any implementation details of `SWeight`, so the checks can be implemented in a separate function.

With these changes, we get this design:
```
def sweight(data, pdfs, yields, range=None, method="summation", return_all=False): ...
```
If `return_all` is False (default), return only the weight function that corresponds to the first pdf, which has to be the signal pdf (this will be documented). If `return_all` is true, return a list of weight functions, one for each pdf.

**Comment by HDembinski** [comment]
Minutes for the call Matt and I just had:
- General agree with this plan, except the following.
- Replace `checks=True` with `fast=False`. If `fast` is false, normalise the pdfs and do expensive checks. If it turns out that the pdfs are already properly normalised, raise a warning that tells the user to set `fast=True`.
- `method` can be removed completely, "integration" in real-life is always worse than "summation", it is only better if you know the true pdfs or when the pdfs do not have any parameters.
